-- T&T Tools complete recovery, Google Drive and six-month archive system
-- Run this once in Supabase SQL Editor before installing the app files.

create extension if not exists pgcrypto;

create table if not exists public.archived_business_monthly (
  id bigint generated by default as identity primary key,
  customer_id bigint,
  customer_name text,
  mobile text,
  shop text not null default '',
  month_start date not null,
  rental_business numeric not null default 0,
  payments_received numeric not null default 0,
  round_off numeric not null default 0,
  opening_due numeric not null default 0,
  opening_credit numeric not null default 0,
  rental_count integer not null default 0,
  payment_count integer not null default 0,
  first_activity date,
  last_activity date,
  archived_at timestamp with time zone not null default now(),
  last_archive_run_id uuid,
  unique (customer_id, shop, month_start)
);

create table if not exists public.archived_tool_monthly (
  id bigint generated by default as identity primary key,
  tool_id bigint,
  tool_name text,
  shop text not null default '',
  month_start date not null,
  movement_count integer not null default 0,
  service_count integer not null default 0,
  service_cost numeric not null default 0,
  first_activity date,
  last_activity date,
  archived_at timestamp with time zone not null default now(),
  last_archive_run_id uuid,
  unique (tool_id, shop, month_start)
);

create table if not exists public.archived_shop_monthly (
  id bigint generated by default as identity primary key,
  shop text not null default '',
  month_start date not null,
  expense_total numeric not null default 0,
  expense_count integer not null default 0,
  sales_revenue numeric not null default 0,
  sales_cost numeric not null default 0,
  sales_profit numeric not null default 0,
  sale_count integer not null default 0,
  shop_cash_received numeric not null default 0,
  cash_entry_count integer not null default 0,
  first_activity date,
  last_activity date,
  archived_at timestamp with time zone not null default now(),
  last_archive_run_id uuid,
  unique (shop, month_start)
);

create table if not exists public.tt_archive_runs (
  id uuid primary key default gen_random_uuid(),
  cutoff_date date not null,
  status text not null default 'running',
  eligible_customer_count integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  started_at timestamp with time zone not null default now(),
  completed_at timestamp with time zone
);

create table if not exists public.tt_backup_audit (
  id uuid primary key default gen_random_uuid(),
  backup_type text not null,
  status text not null,
  file_name text,
  drive_file_id text,
  row_count integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.tt_secure_settings (
  setting_key text primary key,
  encrypted_value text not null,
  updated_at timestamp with time zone not null default now()
);

create index if not exists archived_business_month_idx
  on public.archived_business_monthly (month_start, shop);

create index if not exists archived_business_customer_idx
  on public.archived_business_monthly (customer_id);

create index if not exists archived_tool_month_idx
  on public.archived_tool_monthly (month_start, tool_id);

create index if not exists archived_shop_month_idx
  on public.archived_shop_monthly (month_start, shop);

create index if not exists tt_backup_audit_created_idx
  on public.tt_backup_audit (created_at desc);

create index if not exists rentals_archive_lookup_idx
  on public.rentals (customer_id, end_date)
  where end_date is not null;

create index if not exists payments_archive_lookup_idx
  on public.payments (
    customer_id,
    coalesce(effective_date, payment_date, created_at::date)
  );

create index if not exists movements_archive_lookup_idx
  on public.movements (
    coalesce(movement_date, created_at::date)
  );

create index if not exists services_archive_lookup_idx
  on public.services (
    coalesce(date_in, return_date)
  )
  where date_in is not null or return_date is not null;

revoke all on public.archived_business_monthly from anon, authenticated;
revoke all on public.archived_tool_monthly from anon, authenticated;
revoke all on public.archived_shop_monthly from anon, authenticated;
revoke all on public.tt_archive_runs from anon, authenticated;
revoke all on public.tt_backup_audit from anon, authenticated;
revoke all on public.tt_secure_settings from anon, authenticated;

grant all on public.archived_business_monthly to service_role;
grant all on public.archived_tool_monthly to service_role;
grant all on public.archived_shop_monthly to service_role;
grant all on public.tt_archive_runs to service_role;
grant all on public.tt_backup_audit to service_role;
grant all on public.tt_secure_settings to service_role;

create or replace function public.tt_restore_snapshot(
  snapshot jsonb,
  confirmation_phrase text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target_table text;
  table_names text[] := array[
    'branches',
    'service_centres',
    'customers',
    'tools',
    'sale_items',
    'rentals',
    'payments',
    'movements',
    'services',
    'expenses',
    'sale_entries',
    'shop_cash_received',
    'customer_arrears',
    'rental_edit_history',
    'archived_business_monthly',
    'archived_tool_monthly',
    'archived_shop_monthly'
  ];
  has_identity boolean;
  sequence_name text;
  maximum_id bigint;
  table_payload jsonb;
  restored_rows bigint := 0;
begin
  if confirmation_phrase <> 'RESTORE ALL DATA' then
    raise exception 'Incorrect restore confirmation phrase';
  end if;

  if snapshot is null or jsonb_typeof(snapshot) <> 'object' then
    raise exception 'Recovery snapshot must be a JSON object';
  end if;

  truncate table
    public.rental_edit_history,
    public.payments,
    public.rentals,
    public.movements,
    public.services,
    public.expenses,
    public.sale_entries,
    public.shop_cash_received,
    public.customer_arrears,
    public.sale_items,
    public.tools,
    public.customers,
    public.service_centres,
    public.branches,
    public.archived_business_monthly,
    public.archived_tool_monthly,
    public.archived_shop_monthly
  restart identity cascade;

  foreach target_table in array table_names loop
    table_payload := coalesce(snapshot -> target_table, '[]'::jsonb);

    if jsonb_typeof(table_payload) <> 'array' then
      raise exception 'Snapshot entry % must be an array', target_table;
    end if;

    select exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and information_schema.columns.table_name = target_table
        and is_identity = 'YES'
    )
    into has_identity;

    if has_identity then
      execute format(
        'insert into public.%1$I overriding system value
         select * from jsonb_populate_recordset(null::public.%1$I, $1)',
        target_table
      )
      using table_payload;
    else
      execute format(
        'insert into public.%1$I
         select * from jsonb_populate_recordset(null::public.%1$I, $1)',
        target_table
      )
      using table_payload;
    end if;

    restored_rows :=
      restored_rows + jsonb_array_length(table_payload);

    sequence_name :=
      pg_get_serial_sequence(
        format('public.%I', target_table),
        'id'
      );

    if sequence_name is not null then
      execute format(
        'select max(id)::bigint from public.%I',
        target_table
      )
      into maximum_id;

      if maximum_id is null then
        perform setval(sequence_name::regclass, 1, false);
      else
        perform setval(
          sequence_name::regclass,
          maximum_id,
          true
        );
      end if;
    end if;
  end loop;

  return jsonb_build_object(
    'success', true,
    'restored_rows', restored_rows,
    'restored_tables', array_length(table_names, 1),
    'restored_at', now()
  );
end;
$$;

revoke all on function public.tt_restore_snapshot(jsonb, text)
  from public, anon, authenticated;
grant execute on function public.tt_restore_snapshot(jsonb, text)
  to service_role;

create or replace function public.tt_archive_preview(
  cutoff_date date default ((current_date - interval '6 months')::date)
)
returns jsonb
language sql
security definer
set search_path = public, pg_temp
as $$
with
old_rental_stats as (
  select
    r.customer_id,
    count(*)::integer as rental_count,
    coalesce(sum(r.total_amount), 0)::numeric as old_business,
    min(r.start_date) as first_activity,
    max(r.end_date) as last_activity
  from public.rentals r
  where r.customer_id is not null
    and r.end_date is not null
    and r.end_date <= cutoff_date
    and lower(coalesce(r.status, '')) not in (
      'active', 'live', 'rented', 'ongoing'
    )
  group by r.customer_id
),
old_payment_stats as (
  select
    p.customer_id,
    count(*)::integer as payment_count,
    coalesce(sum(
      case
        when lower(coalesce(p.entry_type, 'payment')) not in (
          'opening_due', 'opening_credit'
        )
        then coalesce(p.amount, 0)
        else 0
      end
    ), 0)::numeric as old_received,
    coalesce(sum(
      case
        when lower(coalesce(p.entry_type, 'payment')) not in (
          'opening_due', 'opening_credit'
        )
        then coalesce(p.discount, 0)
        else 0
      end
    ), 0)::numeric as old_round_off,
    coalesce(sum(
      case
        when lower(coalesce(p.entry_type, 'payment')) = 'opening_due'
        then abs(coalesce(p.amount, 0))
        else 0
      end
    ), 0)::numeric as opening_due,
    coalesce(sum(
      case
        when lower(coalesce(p.entry_type, 'payment')) = 'opening_credit'
        then abs(coalesce(p.amount, 0))
        else 0
      end
    ), 0)::numeric as opening_credit
  from public.payments p
  where p.customer_id is not null
    and coalesce(
      p.effective_date,
      p.payment_date,
      p.created_at::date
    ) <= cutoff_date
  group by p.customer_id
),
carry_over_customers as (
  select distinct r.customer_id
  from public.rentals r
  where r.customer_id is not null
    and r.start_date <= cutoff_date
    and (
      r.end_date is null
      or r.end_date > cutoff_date
      or lower(coalesce(r.status, '')) in (
        'active', 'live', 'rented', 'ongoing'
      )
    )
),
eligible as (
  select
    c.id as customer_id,
    c.customer_name,
    coalesce(c.mobile, '') as mobile,
    rs.rental_count,
    rs.old_business,
    coalesce(ps.old_received, 0) as old_received,
    coalesce(ps.old_round_off, 0) as old_round_off,
    coalesce(ps.opening_due, 0) as opening_due,
    coalesce(ps.opening_credit, 0) as opening_credit,
    (
      coalesce(ps.opening_due, 0)
      - coalesce(ps.opening_credit, 0)
      + rs.old_business
      - coalesce(ps.old_received, 0)
      - coalesce(ps.old_round_off, 0)
    )::numeric as balance_at_cutoff
  from public.customers c
  join old_rental_stats rs
    on rs.customer_id = c.id
  left join old_payment_stats ps
    on ps.customer_id = c.id
  where not exists (
    select 1
    from carry_over_customers cc
    where cc.customer_id = c.id
  )
  and abs(
    coalesce(ps.opening_due, 0)
    - coalesce(ps.opening_credit, 0)
    + rs.old_business
    - coalesce(ps.old_received, 0)
    - coalesce(ps.old_round_off, 0)
  ) <= 0.50
)
select jsonb_build_object(
  'cutoff_date', cutoff_date,
  'eligible_customer_count',
    (select count(*) from eligible),
  'rental_rows',
    (
      select count(*)
      from public.rentals r
      join eligible e on e.customer_id = r.customer_id
      where r.end_date is not null
        and r.end_date <= cutoff_date
    ),
  'payment_rows',
    (
      select count(*)
      from public.payments p
      join eligible e on e.customer_id = p.customer_id
      where coalesce(
        p.effective_date,
        p.payment_date,
        p.created_at::date
      ) <= cutoff_date
    ),
  'edit_history_rows',
    (
      select count(*)
      from public.rental_edit_history h
      join public.rentals r on r.id = h.rental_id
      join eligible e on e.customer_id = r.customer_id
      where r.end_date is not null
        and r.end_date <= cutoff_date
    ),
  'movement_rows',
    (
      select count(*)
      from public.movements m
      where coalesce(m.movement_date, m.created_at::date)
        <= cutoff_date
    ),
  'service_rows',
    (
      select count(*)
      from public.services s
      where coalesce(s.date_in, s.return_date) is not null
        and coalesce(s.date_in, s.return_date)
          <= cutoff_date
    ),
  'expense_rows',
    (
      select count(*)
      from public.expenses e
      where coalesce(e.expense_date, e.created_at::date)
        <= cutoff_date
    ),
  'sale_rows',
    (
      select count(*)
      from public.sale_entries s
      where coalesce(s.sale_date, s.created_at::date)
        <= cutoff_date
    ),
  'cash_rows',
    (
      select count(*)
      from public.shop_cash_received c
      where coalesce(c.received_date, c.created_at::date)
        <= cutoff_date
    ),
  'eligible_customers',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'customer_id', customer_id,
            'customer_name', customer_name,
            'mobile', mobile,
            'old_business', old_business,
            'old_received', old_received,
            'old_round_off', old_round_off,
            'balance_at_cutoff', balance_at_cutoff
          )
          order by old_business desc
        )
        from (
          select *
          from eligible
          order by old_business desc
          limit 200
        ) preview_rows
      ),
      '[]'::jsonb
    )
);
$$;

revoke all on function public.tt_archive_preview(date)
  from public, anon, authenticated;
grant execute on function public.tt_archive_preview(date)
  to service_role;

create or replace function public.tt_archive_execute(
  cutoff_date date,
  confirmation_phrase text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  run_id uuid := gen_random_uuid();
  eligible_count integer := 0;
  rental_count integer := 0;
  payment_count integer := 0;
  edit_count integer := 0;
  movement_count integer := 0;
  service_count integer := 0;
  expense_count integer := 0;
  sale_count integer := 0;
  cash_count integer := 0;
begin
  if confirmation_phrase <> 'ARCHIVE SETTLED DATA' then
    raise exception 'Incorrect archive confirmation phrase';
  end if;

  create temporary table tt_tmp_eligible_customers
  on commit drop
  as
  with
  old_rental_stats as (
    select
      r.customer_id,
      count(*)::integer as rental_count,
      coalesce(sum(r.total_amount), 0)::numeric as old_business
    from public.rentals r
    where r.customer_id is not null
      and r.end_date is not null
      and r.end_date <= cutoff_date
      and lower(coalesce(r.status, '')) not in (
        'active', 'live', 'rented', 'ongoing'
      )
    group by r.customer_id
  ),
  old_payment_stats as (
    select
      p.customer_id,
      coalesce(sum(
        case
          when lower(coalesce(p.entry_type, 'payment')) not in (
            'opening_due', 'opening_credit'
          )
          then coalesce(p.amount, 0)
          else 0
        end
      ), 0)::numeric as old_received,
      coalesce(sum(
        case
          when lower(coalesce(p.entry_type, 'payment')) not in (
            'opening_due', 'opening_credit'
          )
          then coalesce(p.discount, 0)
          else 0
        end
      ), 0)::numeric as old_round_off,
      coalesce(sum(
        case
          when lower(coalesce(p.entry_type, 'payment')) = 'opening_due'
          then abs(coalesce(p.amount, 0))
          else 0
        end
      ), 0)::numeric as opening_due,
      coalesce(sum(
        case
          when lower(coalesce(p.entry_type, 'payment')) = 'opening_credit'
          then abs(coalesce(p.amount, 0))
          else 0
        end
      ), 0)::numeric as opening_credit
    from public.payments p
    where p.customer_id is not null
      and coalesce(
        p.effective_date,
        p.payment_date,
        p.created_at::date
      ) <= cutoff_date
    group by p.customer_id
  ),
  carry_over_customers as (
    select distinct r.customer_id
    from public.rentals r
    where r.customer_id is not null
      and r.start_date <= cutoff_date
      and (
        r.end_date is null
        or r.end_date > cutoff_date
        or lower(coalesce(r.status, '')) in (
          'active', 'live', 'rented', 'ongoing'
        )
      )
  )
  select
    c.id as customer_id
  from public.customers c
  join old_rental_stats rs
    on rs.customer_id = c.id
  left join old_payment_stats ps
    on ps.customer_id = c.id
  where not exists (
    select 1
    from carry_over_customers cc
    where cc.customer_id = c.id
  )
  and abs(
    coalesce(ps.opening_due, 0)
    - coalesce(ps.opening_credit, 0)
    + rs.old_business
    - coalesce(ps.old_received, 0)
    - coalesce(ps.old_round_off, 0)
  ) <= 0.50;

  select count(*)
  into eligible_count
  from tt_tmp_eligible_customers;

  insert into public.tt_archive_runs (
    id,
    cutoff_date,
    status,
    eligible_customer_count
  )
  values (
    run_id,
    cutoff_date,
    'running',
    eligible_count
  );

  insert into public.archived_business_monthly (
    customer_id,
    customer_name,
    mobile,
    shop,
    month_start,
    rental_business,
    rental_count,
    first_activity,
    last_activity,
    last_archive_run_id
  )
  select
    r.customer_id,
    max(c.customer_name),
    max(coalesce(c.mobile, '')),
    coalesce(r.shop, ''),
    date_trunc('month', r.end_date)::date,
    coalesce(sum(r.total_amount), 0),
    count(*)::integer,
    min(r.start_date),
    max(r.end_date),
    run_id
  from public.rentals r
  join tt_tmp_eligible_customers e
    on e.customer_id = r.customer_id
  join public.customers c
    on c.id = r.customer_id
  where r.end_date is not null
    and r.end_date <= cutoff_date
  group by
    r.customer_id,
    coalesce(r.shop, ''),
    date_trunc('month', r.end_date)::date
  on conflict (customer_id, shop, month_start)
  do update set
    customer_name = excluded.customer_name,
    mobile = excluded.mobile,
    rental_business =
      public.archived_business_monthly.rental_business
      + excluded.rental_business,
    rental_count =
      public.archived_business_monthly.rental_count
      + excluded.rental_count,
    first_activity = case
      when public.archived_business_monthly.first_activity is null
        then excluded.first_activity
      when excluded.first_activity is null
        then public.archived_business_monthly.first_activity
      else least(
        public.archived_business_monthly.first_activity,
        excluded.first_activity
      )
    end,
    last_activity = case
      when public.archived_business_monthly.last_activity is null
        then excluded.last_activity
      when excluded.last_activity is null
        then public.archived_business_monthly.last_activity
      else greatest(
        public.archived_business_monthly.last_activity,
        excluded.last_activity
      )
    end,
    archived_at = now(),
    last_archive_run_id = run_id;

  insert into public.archived_business_monthly (
    customer_id,
    customer_name,
    mobile,
    shop,
    month_start,
    payments_received,
    round_off,
    opening_due,
    opening_credit,
    payment_count,
    first_activity,
    last_activity,
    last_archive_run_id
  )
  select
    p.customer_id,
    max(c.customer_name),
    max(coalesce(c.mobile, '')),
    coalesce(p.shop, ''),
    date_trunc(
      'month',
      coalesce(
        p.effective_date,
        p.payment_date,
        p.created_at::date
      )
    )::date,
    coalesce(sum(
      case
        when lower(coalesce(p.entry_type, 'payment')) not in (
          'opening_due', 'opening_credit'
        )
        then coalesce(p.amount, 0)
        else 0
      end
    ), 0),
    coalesce(sum(
      case
        when lower(coalesce(p.entry_type, 'payment')) not in (
          'opening_due', 'opening_credit'
        )
        then coalesce(p.discount, 0)
        else 0
      end
    ), 0),
    coalesce(sum(
      case
        when lower(coalesce(p.entry_type, 'payment')) = 'opening_due'
        then abs(coalesce(p.amount, 0))
        else 0
      end
    ), 0),
    coalesce(sum(
      case
        when lower(coalesce(p.entry_type, 'payment')) = 'opening_credit'
        then abs(coalesce(p.amount, 0))
        else 0
      end
    ), 0),
    count(*)::integer,
    min(coalesce(
      p.effective_date,
      p.payment_date,
      p.created_at::date
    )),
    max(coalesce(
      p.effective_date,
      p.payment_date,
      p.created_at::date
    )),
    run_id
  from public.payments p
  join tt_tmp_eligible_customers e
    on e.customer_id = p.customer_id
  join public.customers c
    on c.id = p.customer_id
  where coalesce(
    p.effective_date,
    p.payment_date,
    p.created_at::date
  ) <= cutoff_date
  group by
    p.customer_id,
    coalesce(p.shop, ''),
    date_trunc(
      'month',
      coalesce(
        p.effective_date,
        p.payment_date,
        p.created_at::date
      )
    )::date
  on conflict (customer_id, shop, month_start)
  do update set
    customer_name = excluded.customer_name,
    mobile = excluded.mobile,
    payments_received =
      public.archived_business_monthly.payments_received
      + excluded.payments_received,
    round_off =
      public.archived_business_monthly.round_off
      + excluded.round_off,
    opening_due =
      public.archived_business_monthly.opening_due
      + excluded.opening_due,
    opening_credit =
      public.archived_business_monthly.opening_credit
      + excluded.opening_credit,
    payment_count =
      public.archived_business_monthly.payment_count
      + excluded.payment_count,
    first_activity = case
      when public.archived_business_monthly.first_activity is null
        then excluded.first_activity
      when excluded.first_activity is null
        then public.archived_business_monthly.first_activity
      else least(
        public.archived_business_monthly.first_activity,
        excluded.first_activity
      )
    end,
    last_activity = case
      when public.archived_business_monthly.last_activity is null
        then excluded.last_activity
      when excluded.last_activity is null
        then public.archived_business_monthly.last_activity
      else greatest(
        public.archived_business_monthly.last_activity,
        excluded.last_activity
      )
    end,
    archived_at = now(),
    last_archive_run_id = run_id;

  insert into public.archived_tool_monthly (
    tool_id,
    tool_name,
    shop,
    month_start,
    movement_count,
    first_activity,
    last_activity,
    last_archive_run_id
  )
  select
    m.tool_id,
    max(t.tool_name),
    coalesce(m.to_location, m.from_location, ''),
    date_trunc(
      'month',
      coalesce(m.movement_date, m.created_at::date)
    )::date,
    count(*)::integer,
    min(coalesce(m.movement_date, m.created_at::date)),
    max(coalesce(m.movement_date, m.created_at::date)),
    run_id
  from public.movements m
  left join public.tools t on t.id = m.tool_id
  where coalesce(m.movement_date, m.created_at::date)
    <= cutoff_date
  group by
    m.tool_id,
    coalesce(m.to_location, m.from_location, ''),
    date_trunc(
      'month',
      coalesce(m.movement_date, m.created_at::date)
    )::date
  on conflict (tool_id, shop, month_start)
  do update set
    tool_name = excluded.tool_name,
    movement_count =
      public.archived_tool_monthly.movement_count
      + excluded.movement_count,
    first_activity = least(
      public.archived_tool_monthly.first_activity,
      excluded.first_activity
    ),
    last_activity = greatest(
      public.archived_tool_monthly.last_activity,
      excluded.last_activity
    ),
    archived_at = now(),
    last_archive_run_id = run_id;

  insert into public.archived_tool_monthly (
    tool_id,
    tool_name,
    shop,
    month_start,
    service_count,
    service_cost,
    first_activity,
    last_activity,
    last_archive_run_id
  )
  select
    s.tool_id,
    max(coalesce(t.tool_name, s.tool_name)),
    coalesce(s.return_branch, s.from_branch, ''),
    date_trunc(
      'month',
      coalesce(s.date_in, s.return_date)
    )::date,
    count(*)::integer,
    coalesce(sum(coalesce(s.cost, s.amount, 0)), 0),
    min(coalesce(s.date_out, s.out_date)),
    max(coalesce(s.date_in, s.return_date)),
    run_id
  from public.services s
  left join public.tools t on t.id = s.tool_id
  where coalesce(s.date_in, s.return_date) is not null
    and coalesce(s.date_in, s.return_date)
      <= cutoff_date
  group by
    s.tool_id,
    coalesce(s.return_branch, s.from_branch, ''),
    date_trunc(
      'month',
      coalesce(s.date_in, s.return_date)
    )::date
  on conflict (tool_id, shop, month_start)
  do update set
    tool_name = excluded.tool_name,
    service_count =
      public.archived_tool_monthly.service_count
      + excluded.service_count,
    service_cost =
      public.archived_tool_monthly.service_cost
      + excluded.service_cost,
    first_activity = case
      when public.archived_tool_monthly.first_activity is null
        then excluded.first_activity
      when excluded.first_activity is null
        then public.archived_tool_monthly.first_activity
      else least(
        public.archived_tool_monthly.first_activity,
        excluded.first_activity
      )
    end,
    last_activity = case
      when public.archived_tool_monthly.last_activity is null
        then excluded.last_activity
      when excluded.last_activity is null
        then public.archived_tool_monthly.last_activity
      else greatest(
        public.archived_tool_monthly.last_activity,
        excluded.last_activity
      )
    end,
    archived_at = now(),
    last_archive_run_id = run_id;

  insert into public.archived_shop_monthly (
    shop,
    month_start,
    expense_total,
    expense_count,
    first_activity,
    last_activity,
    last_archive_run_id
  )
  select
    coalesce(e.shop, ''),
    date_trunc(
      'month',
      coalesce(e.expense_date, e.created_at::date)
    )::date,
    coalesce(sum(e.amount), 0),
    count(*)::integer,
    min(coalesce(e.expense_date, e.created_at::date)),
    max(coalesce(e.expense_date, e.created_at::date)),
    run_id
  from public.expenses e
  where coalesce(e.expense_date, e.created_at::date)
    <= cutoff_date
  group by
    coalesce(e.shop, ''),
    date_trunc(
      'month',
      coalesce(e.expense_date, e.created_at::date)
    )::date
  on conflict (shop, month_start)
  do update set
    expense_total =
      public.archived_shop_monthly.expense_total
      + excluded.expense_total,
    expense_count =
      public.archived_shop_monthly.expense_count
      + excluded.expense_count,
    first_activity = least(
      public.archived_shop_monthly.first_activity,
      excluded.first_activity
    ),
    last_activity = greatest(
      public.archived_shop_monthly.last_activity,
      excluded.last_activity
    ),
    archived_at = now(),
    last_archive_run_id = run_id;

  insert into public.archived_shop_monthly (
    shop,
    month_start,
    sales_revenue,
    sales_cost,
    sales_profit,
    sale_count,
    first_activity,
    last_activity,
    last_archive_run_id
  )
  select
    coalesce(s.shop, ''),
    date_trunc(
      'month',
      coalesce(s.sale_date, s.created_at::date)
    )::date,
    coalesce(sum(s.total_sale), 0),
    coalesce(sum(s.total_cost), 0),
    coalesce(sum(s.profit), 0),
    count(*)::integer,
    min(coalesce(s.sale_date, s.created_at::date)),
    max(coalesce(s.sale_date, s.created_at::date)),
    run_id
  from public.sale_entries s
  where coalesce(s.sale_date, s.created_at::date)
    <= cutoff_date
  group by
    coalesce(s.shop, ''),
    date_trunc(
      'month',
      coalesce(s.sale_date, s.created_at::date)
    )::date
  on conflict (shop, month_start)
  do update set
    sales_revenue =
      public.archived_shop_monthly.sales_revenue
      + excluded.sales_revenue,
    sales_cost =
      public.archived_shop_monthly.sales_cost
      + excluded.sales_cost,
    sales_profit =
      public.archived_shop_monthly.sales_profit
      + excluded.sales_profit,
    sale_count =
      public.archived_shop_monthly.sale_count
      + excluded.sale_count,
    first_activity = least(
      public.archived_shop_monthly.first_activity,
      excluded.first_activity
    ),
    last_activity = greatest(
      public.archived_shop_monthly.last_activity,
      excluded.last_activity
    ),
    archived_at = now(),
    last_archive_run_id = run_id;

  insert into public.archived_shop_monthly (
    shop,
    month_start,
    shop_cash_received,
    cash_entry_count,
    first_activity,
    last_activity,
    last_archive_run_id
  )
  select
    coalesce(c.shop, ''),
    date_trunc(
      'month',
      coalesce(c.received_date, c.created_at::date)
    )::date,
    coalesce(sum(c.amount), 0),
    count(*)::integer,
    min(coalesce(c.received_date, c.created_at::date)),
    max(coalesce(c.received_date, c.created_at::date)),
    run_id
  from public.shop_cash_received c
  where coalesce(c.received_date, c.created_at::date)
    <= cutoff_date
  group by
    coalesce(c.shop, ''),
    date_trunc(
      'month',
      coalesce(c.received_date, c.created_at::date)
    )::date
  on conflict (shop, month_start)
  do update set
    shop_cash_received =
      public.archived_shop_monthly.shop_cash_received
      + excluded.shop_cash_received,
    cash_entry_count =
      public.archived_shop_monthly.cash_entry_count
      + excluded.cash_entry_count,
    first_activity = least(
      public.archived_shop_monthly.first_activity,
      excluded.first_activity
    ),
    last_activity = greatest(
      public.archived_shop_monthly.last_activity,
      excluded.last_activity
    ),
    archived_at = now(),
    last_archive_run_id = run_id;

  select count(*) into edit_count
  from public.rental_edit_history h
  join public.rentals r on r.id = h.rental_id
  join tt_tmp_eligible_customers e
    on e.customer_id = r.customer_id
  where r.end_date is not null
    and r.end_date <= cutoff_date;

  delete from public.rental_edit_history h
  using public.rentals r, tt_tmp_eligible_customers e
  where h.rental_id = r.id
    and e.customer_id = r.customer_id
    and r.end_date is not null
    and r.end_date <= cutoff_date;

  select count(*) into payment_count
  from public.payments p
  join tt_tmp_eligible_customers e
    on e.customer_id = p.customer_id
  where coalesce(
    p.effective_date,
    p.payment_date,
    p.created_at::date
  ) <= cutoff_date;

  delete from public.payments p
  using tt_tmp_eligible_customers e
  where e.customer_id = p.customer_id
    and coalesce(
      p.effective_date,
      p.payment_date,
      p.created_at::date
    ) <= cutoff_date;

  select count(*) into rental_count
  from public.rentals r
  join tt_tmp_eligible_customers e
    on e.customer_id = r.customer_id
  where r.end_date is not null
    and r.end_date <= cutoff_date;

  delete from public.rentals r
  using tt_tmp_eligible_customers e
  where e.customer_id = r.customer_id
    and r.end_date is not null
    and r.end_date <= cutoff_date;

  select count(*) into movement_count
  from public.movements m
  where coalesce(m.movement_date, m.created_at::date)
    <= cutoff_date;

  delete from public.movements m
  where coalesce(m.movement_date, m.created_at::date)
    <= cutoff_date;

  select count(*) into service_count
  from public.services s
  where coalesce(s.date_in, s.return_date) is not null
    and coalesce(s.date_in, s.return_date)
      <= cutoff_date;

  delete from public.services s
  where coalesce(s.date_in, s.return_date) is not null
    and coalesce(s.date_in, s.return_date)
      <= cutoff_date;

  select count(*) into expense_count
  from public.expenses e
  where coalesce(e.expense_date, e.created_at::date)
    <= cutoff_date;

  delete from public.expenses e
  where coalesce(e.expense_date, e.created_at::date)
    <= cutoff_date;

  select count(*) into sale_count
  from public.sale_entries s
  where coalesce(s.sale_date, s.created_at::date)
    <= cutoff_date;

  delete from public.sale_entries s
  where coalesce(s.sale_date, s.created_at::date)
    <= cutoff_date;

  select count(*) into cash_count
  from public.shop_cash_received c
  where coalesce(c.received_date, c.created_at::date)
    <= cutoff_date;

  delete from public.shop_cash_received c
  where coalesce(c.received_date, c.created_at::date)
    <= cutoff_date;

  update public.tt_archive_runs
  set
    status = 'completed',
    completed_at = now(),
    details = jsonb_build_object(
      'rentals_deleted', rental_count,
      'payments_deleted', payment_count,
      'edit_history_deleted', edit_count,
      'movements_deleted', movement_count,
      'services_deleted', service_count,
      'expenses_deleted', expense_count,
      'sales_deleted', sale_count,
      'cash_rows_deleted', cash_count
    )
  where id = run_id;

  analyze public.rentals;
  analyze public.payments;
  analyze public.rental_edit_history;
  analyze public.movements;
  analyze public.services;
  analyze public.expenses;
  analyze public.sale_entries;
  analyze public.shop_cash_received;

  return jsonb_build_object(
    'success', true,
    'archive_run_id', run_id,
    'cutoff_date', cutoff_date,
    'eligible_customers', eligible_count,
    'rentals_deleted', rental_count,
    'payments_deleted', payment_count,
    'edit_history_deleted', edit_count,
    'movements_deleted', movement_count,
    'services_deleted', service_count,
    'expenses_deleted', expense_count,
    'sales_deleted', sale_count,
    'cash_rows_deleted', cash_count,
    'completed_at', now()
  );
exception
  when others then
    update public.tt_archive_runs
    set
      status = 'failed',
      completed_at = now(),
      details = jsonb_build_object(
        'error', sqlerrm
      )
    where id = run_id;

    raise;
end;
$$;

revoke all on function public.tt_archive_execute(date, text)
  from public, anon, authenticated;
grant execute on function public.tt_archive_execute(date, text)
  to service_role;
